5 module tasks
js-tasks-ru/jsbasic-20220419-2_korotkikh-andrey pull request #7
Opened 2022-05-22 19:14 UTC by korotkikhandrey

5 module tasks

2022-05-22 19:14 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-05-22 19:32 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-22 23:55 UTC, koalex requested changes
Нужно решить **6-1**

2022-05-23 07:16 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-05-23 07:18 UTC, korotkikhandrey commented
>

2022-05-23 07:18 UTC, closed without merging